<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BanquePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanquePhotoRepository extends EntityRepository
{
    public function findBanque($typeId = null)
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder()
            ->addSelect('b')
            ->from('App\Core\Entity\BanquePhoto', 'b')
            ->innerJoin('b.banquePhotoType', 'bpt')
            ->where('b.client is null')
            ->andWhere('b.confirmer = 1')
            ->andWhere('b.public = 1');

        if ($typeId != null) {
            $requete->andWhere('bpt.id = :banque_photo_type_id');
            $requete->setParameter(':banque_photo_type_id', $typeId);
        }

        return $requete->getQuery()->getResult();
    }

    public function findByClient($clientId)
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('b');
        $requete->from('App\Core\Entity\BanquePhoto', 'b');
        $requete->where('b.client = :client');
        $requete->andWhere("b.confirmer = 1");

        $requete->setParameter(':client', $clientId);

        return $requete->getQuery()->getResult();
    }

    public function findForInscription(?int $clientId = null)
    {
        $files = array();

        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder()
            ->addSelect('b')
            ->from('App\Core\Entity\BanquePhoto', 'b')
            ->innerJoin('b.banquePhotoType', 'bpt')
            ->where('b.confirmer = 1')
            ->orderBy('b.client', 'asc');

        if ($clientId != null) {
            $requete->where('((b.client is null AND b.public = 1) OR IDENTITY(b.client) = :client)');
            $requete->setParameter(':client', $clientId);
        } else {
            $requete->where('(b.client is null AND b.public = 1)');
        }
        $requete->andWhere('(b.deleted is null OR b.deleted = 0)');



        $res = $requete->getQuery()->getResult();
        foreach($res as $item) {
            $largeur = $item->getLargeur() !== null ? $item->getLargeur() : 0;
            $hauteur = $item->getHauteur() !== null ? $item->getHauteur() : 0;
            $type = $item->getBanquePhotoType() !== null ? $item->getBanquePhotoType() : 0;
            $nom = $item->getNom();
            $photo = $item->getPhoto();

            if(preg_match('/^[0-9]{8,}-/', $photo, $matches) == 1) {
                $photo = str_replace($matches[0], '', $photo);
            }

            $key = ($item->getPublic() ? '0' : '1') . '#' . ($item->getDateCreation() ? $item->getDateCreation()->format('U') : '0000000000') . '#' . $largeur . '#' . $hauteur . '#' . $type . '#' . $photo;

            if(!isset($files[$key])){
                $files[$key] = $item;
            }
        }

        krsort($files);

        return array_values($files);
    }

}
