<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BesoinEauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BesoinEauRepository extends EntityRepository
{
    public function recupValeurMax()
    {
        $query = $this->createQueryBuilder('be');
        $query->select('be, MAX(be.valeur) AS valeur_max');
        $query->setMaxResults(1);
        $query->orderBy('valeur_max', 'DESC');

        return $query->getQuery()->getResult();
    }

    public function findByValeurs($besoinEauValeurs)
    {
        $res = array();

        if (is_array($besoinEauValeurs) && count($besoinEauValeurs) > 0) {
            $em = $this->getEntityManager();
            $requete = $em->createQueryBuilder();
            $requete->addSelect('be');
            $requete->from('App\Core\Entity\BesoinEau', 'be');
            $requete->where('be.valeur IN(:besoinEauValeurs)');
            $requete->setParameter(':besoinEauValeurs', $besoinEauValeurs);

            $res = $requete->getQuery()->getResult();
        }

        return $res;
    }
}
