<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->createQueryBuilder('c')->addOrderBy('c.nom', "ASC");
    }

    public function recupNomsOrdonne($type)
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('c.id, c.nom');
        $requete->from('App\Core\Entity\Categorie', 'c');
        if ($type == 'plante') {
            $requete->where("c.entiteType = 'plante'");
            $requete->orWhere("c.entiteType = 'tout'");
        } elseif ($type == 'objet') {
            $requete->where("c.entiteType = 'objet'");
            $requete->orWhere("c.entiteType = 'tout'");
        }
        $requete->orderBy('c.nom', 'ASC');

        return $requete->getQuery()->getArrayResult();
    }

    public function findAllArray()
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('c.nom');
        $requete->from('App\Core\Entity\Categorie', 'c');
        $list = $requete->getQuery()->getArrayResult();

        $tab = array();
        foreach ($list as $value) {
            $tab[] = $value['nom'];
        }

        return $tab;
    }

}
