<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientCodePromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientCodePromoRepository extends EntityRepository
{
}
