<?php

namespace App\Core\Repository;

use App\Core\Entity\Cms;
use Doctrine\ORM\EntityRepository;

/**
 * CmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsRepository extends EntityRepository
{
    public function findTranslatedUrl(Cms $cms, $locale) {
        $translatedUrl = null;
        if($locale != 'fr') {
            $query = $this->_em->createQueryBuilder();
            $query->select('c.id, ct.content')
                ->from(\App\Core\Entity\Cms::class, 'c')
                ->leftJoin(
                    \App\Core\Entity\Translation\Cms::class,
                    'ct',
                    \Doctrine\ORM\Query\Expr\Join::WITH,
                    $query->expr()->andX(
                        $query->expr()->eq("IDENTITY(ct.object)", "c.id"),
                        $query->expr()->eq("ct.field", "'url'")
                    )
                )
                ->where('c.id = :entityId')
                ->andWhere('ct.locale = :locale')
                ->andWhere('ct.content IS NOT NULL')
                ->setParameters(array(
                    'entityId' => $cms->getId(),
                    'locale' => $locale
                ));

            $res = $query->getQuery()->getOneOrNullResult();
            if($res !== null && isset($res['content']) && trim($res['content']) != "") {
                $translatedUrl = $res['content'];
            }
        } else {
            if($cms->getUrl() !== null && trim($cms->getUrl()) != "") {
                $translatedUrl = $cms->getUrl();
            }
        }

        return $translatedUrl;
    }
}
