<?php

namespace App\Core\Repository;

use DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * CodePromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePromoRepository extends EntityRepository
{
    public function codePromoControleValidite($code, $client, $offre)
    {
        $em = $this->getEntityManager();

        $codePromo = $em->getRepository('App\Core\Entity\CodePromo')->findOneByCode($code);
        $dateActuelle = new DateTime();
        if ($codePromo) {
            $offreCompatible = false;
            foreach ($codePromo->getOffres() as $offrePromo) {
                if ($offrePromo == $offre) {
                    $offreCompatible = true;
                }
            }
            if ($codePromo->getOffres()->isEmpty()) {
                $offreCompatible = true;
            }
            if ($codePromo->getActif() == true) {
                if ((!$codePromo->getDateDebut() || $codePromo->getDateDebut(
                        ) < $dateActuelle) && (!$codePromo->getDateFin() || $codePromo->getDateFin() > $dateActuelle)) {
                    if ($offreCompatible) {
                        if (!$codePromo->getNbUtilisations() || !$codePromo->getNbUtilisationsCompteur(
                            ) || $codePromo->getNbUtilisations() >= $codePromo->getNbUtilisationsCompteur()) {
                            if ($codePromo->getNbUtilisationsParClient()) {
                                $requete = $this->createQueryBuilder('cp')
                                    ->select('cp')
                                    ->leftJoin('cp.clientCodePromos', 'ccp')
                                    ->where('ccp.client = :client_id')
                                    ->setParameter('client_id', $client->getId());

                                if (count($requete->getQuery()->getResult()) <= $codePromo->getNbUtilisationsParClient(
                                    )) {
                                    $valide = true;
                                    $message = null;
                                } else {
                                    $valide = false;
                                    $message = "Vous avez déjà utilisé ce Code Promo" . $codePromo->getNbUtilisationsParClient(
                                        ) . " fois, vous ne pouvez plus l'utiliser. Essayer un autre code promo.";
                                }
                            } else {
                                $valide = true;
                                $message = null;
                            }
                        } else {
                            $valide = false;
                            $message = "Ce code Promo n'est plus valide. Essayer un autre code promo.";
                        }
                    } else {
                        $valide = false;
                        $message = "Ce code Promo n'est pas utilisable sur cette offre. Essayer un autre code promo.";
                    }
                } else {
                    $valide = false;
                    $message = "Ce code Promo n'est pas valide. Essayer un autre code promo.";
                }
            } else {
                $valide = false;
                $message = "Ce code Promo n'est pas valide. Essayer un autre code promo.";
            }
        } else {
            $valide = false;
            $message = "Ce code Promo n'est pas valide. Essayer un autre code promo.";
        }

        $retour = array('valide' => $valide, 'message' => $message);

        return $retour;
    }
}
