<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CouleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouleurRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->createQueryBuilder('c')->addOrderBy('c.nom', "ASC");
    }

    public function recupNomsOrdonne()
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('c.id, c.nom');
        $requete->from('App\Core\Entity\Couleur', 'c');
        $requete->orderBy('c.nom', 'ASC');

        return $requete->getQuery()->getArrayResult();
    }

    public function findAllArray()
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('c.nom');
        $requete->from('App\Core\Entity\Couleur', 'c');
        $list = $requete->getQuery()->getArrayResult();

        $tab = array();
        foreach ($list as $value) {
            $tab[] = $value['nom'];
        }

        return $tab;
    }

}
