<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CreationEntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreationEntiteRepository extends EntityRepository
{
    public function deleteOldEntites($creationId, $notIn)
    {
        $em = $this->getEntityManager();

        $requete = $this->createQueryBuilder('ce')
            ->where('ce.creation = :creation_id');

        $requete->setParameter(':creation_id', $creationId);

        if ($notIn != null && count($notIn) > 0) {
            $requete->andWhere('ce.id NOT IN (:creation_entites_id)');
            $requete->setParameter(':creation_entites_id', $notIn);
        }

        $results = $requete->getQuery()->getResult();
        foreach ($results as $result) {
            $em->remove($result);
            $em->flush();
        }
    }
}
