<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CreationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreationRepository extends EntityRepository
{
    public function getTotal($creationId)
    {
        $requete = $this->createQueryBuilder('c')
            ->select('SUM(e.prixMini) as total')
            ->innerJoin('c.creationEntites', 'ce')
            ->innerJoin('ce.entite', 'e')
            ->where('c.id = :creation_id')
            ->andWhere('ce.visibilite = 1');

        $requete->setParameter(':creation_id', $creationId);

        $total = $requete->getQuery()->getSingleScalarResult();

        return $total;
    }
}
