<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntitePhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitePhotoRepository extends EntityRepository
{

    public function getOrdoredEntitePhoto($entiteId)
    {
        $requete = $this->createQueryBuilder('ep')
            ->select('ep')
            ->leftJoin('ep.entite', 'e')
            ->leftJoin('ep.annee', 'an')
            ->leftJoin('ep.entitePhotoEtat', 'epe')
            ->where('e.id = :entite_id')
            ->orderBy('an.id, epe.id');

        $requete->setParameter(':entite_id', $entiteId);

        return $requete->getQuery()->getResult();
    }

    public function findWithSpaceInPhotoName()
    {
        $requete = $this->createQueryBuilder('ep')
            ->select('ep')
            ->where('ep.photo LIKE :space')
            ->setParameter(':space', '% %');

        return $requete->getQuery()->getResult();
    }

}
