<?php

namespace App\Core\Repository;

use App\Core\Entity\Entite;
use App\Core\Entity\EntitePhoto;
use App\Core\Entity\Rusticite;
use Doctrine\ORM\EntityRepository;


/**
 * EntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntiteRepository extends EntityRepository
{

    /**
     *
     * @param type $entiteType
     * @param type $search
     * @param type $precipitationMax
     * @param type $nbResultat
     * @param type $depart
     * @param type $return
     * @param type $creationTypeId
     * @param type $surface
     * @return type
     *
     */
    public function recupDepuisFiltre(
        $entiteType,
        $search,
        $precipitationMax = null,
        $nbResultat = 16,
        $depart = 0,
        $return,
        $creationTypeId,
        $surface,
        $locale = "fr"
    )
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('e, ep');
        $requete->from('App\Core\Entity\Entite', 'e');
        $requete->innerJoin('e.entiteType', 'et');
        $requete->innerJoin('e.entitePhotos', 'ep');
        $requete->leftJoin('e.besoinEauMultiples', 'bm');
        $requete->leftJoin('bm.precipitations', 'pr');

        if ($locale != "fr") {
            $requete->leftJoin("e.translations", "trnom", "with", "trnom.object = e.id and trnom.field = 'nom' and trnom.locale = '" . $locale . "'");
            $requete->leftJoin("e.translations", "trnonvern", "with", "trnonvern.object = e.id and trnonvern.field = 'nomVernaculaire' and trnonvern.locale = '" . $locale . "'");
        }

        //$requete->leftJoin('e.besoinEau', 'be');
        $requete->leftJoin('e.creationTypes', 'ct');
        $requete->leftJoin('e.rusticiteMultiples', 'rm');

        if (!empty($search['couleur'])) {
            $requete->leftJoin('e.couleurs', 'co');
        }
        $requete->leftJoin('e.couleurFleurs', 'cof');
        if (!empty($search['categories'])) {
            $requete->leftJoin('e.categories', 'ca');
        }
        if (!empty($search['style'])) {
            $requete->leftJoin('e.styles', 's');
        }
        if (!empty($search['mois'])) {
            $requete->leftJoin('e.mois', 'm');
        }
        if (!empty($search['entretien'])) {
            $requete->leftJoin('e.entretien', 'en');
        }
        if (!empty($search['sol'])) {
            $requete->leftJoin('e.typeSols', 'so');
        }
        if (!empty($search['ensoleillement'])) {
            $requete->leftJoin('e.ensoleillements', 'ens');
        }
        if (!empty($search['entite_sous_type_multiples'])) {
            $requete->leftJoin('e.entiteSousTypeMultiples', 'est');
        }
        if (!empty($search['marque'])) {
            $requete->leftJoin('e.marque', 'mar');
        }
        if (!empty($search['matiere'])) {
            $requete->leftJoin('e.matieres', 'mat');
        }
        if (!empty($search['eauMultiples'])) {
            $requete->leftJoin('bm.besoinEauGroupe', 'beg');
        }
        //$requete->leftJoin('be.besoinEauGroupe', 'beg');
        if ($entiteType->getId() == 2) {
            $requete->leftJoin('e.composition', 'comp');
        }


        $requete->where('e.entiteType = :entite_type');
        $requete->setParameter(':entite_type', $entiteType);

        $requete->andWhere('ep.hauteurEntite > 0');
        $requete->andWhere('e.actif = 1');

        if (!empty($search['nom'])) {
            if ($locale == "fr") {
                $orModule = $requete->expr()->orX();
                $orModule->add($requete->expr()->like('lower(e.nom)', ':nom'));
                $orModule->add($requete->expr()->like('lower(e.nomVernaculaire)', ':nom_vernaculaire'));
                $requete->andWhere($orModule);
                $requete->setParameter(':nom', '%' . mb_strtolower($search['nom']) . '%');
                $requete->setParameter(':nom_vernaculaire', '%' . mb_strtolower($search['nom']) . '%');
            } else {
                $orModule = $requete->expr()->orX();
                $orModule->add($requete->expr()->like('lower(trnom.content)', ':nom'));
                $orModule->add($requete->expr()->like('lower(trnonvern.content)', ':nom_vernaculaire'));
                $orModule->add($requete->expr()->like('lower(e.nom)', ':nom'));
                $orModule->add($requete->expr()->like('lower(e.nomVernaculaire)', ':nom_vernaculaire'));
                $requete->andWhere($orModule);
                $requete->setParameter(':nom', '%' . mb_strtolower($search['nom']) . '%');
                $requete->setParameter(':nom_vernaculaire', '%' . mb_strtolower($search['nom']) . '%');
            }
        }
        if (!empty($search['couleur'])) {
            $requete->andWhere('(co.id = :couleur OR cof.id = :couleur)');
            $requete->setParameter(':couleur', $search['couleur']);
        }
        if (!empty($search['categories'])) {
            if (count($search['categories']) > 1) {
                $requete->andWhere('ca.id in (:categories)');
                $requete->setParameter(':categories', $search['categories']);
            } else {
                $requete->andWhere('ca.id = :categories');
                $requete->setParameter(':categories', $search['categories'][0]);
            }
        }
        if (!empty($search['style'])) {
            $requete->andWhere('s.id = :style');
            $requete->setParameter(':style', $search['style']);
        }
        if (!empty($search['mois'])) {
            $requete->andWhere('m.id = :mois');
            $requete->setParameter(':mois', $search['mois']);
        }
        if (!empty($search['sol'])) {
            $requete->andWhere('so.id = :type_sol');
            $requete->setParameter(':type_sol', $search['sol']);
        }
        if (!empty($search['ensoleillement'])) {
            $requete->andWhere('ens.id = :ensoleillement');
            $requete->setParameter(':ensoleillement', $search['ensoleillement']);
        }
        if (!empty($search['entretien'])) {
            $requete->andWhere('en.id = :entretien');
            $requete->setParameter(':entretien', $search['entretien']);
        }
        if (!empty($search['toxique'])) {
            $requete->andWhere('e.toxiqueAlimentaire = :toxique');
            $requete->setParameter(':toxique', $search['toxique']);
        }
        if (!empty($search['caduc'])) {
            $requete->andWhere('e.caducPersistant = :caduc');
            $requete->setParameter(':caduc', $search['caduc']);
        }
        if (!empty($search['eauMultiples'])) {
            if (count($search['eauMultiples']) > 1) {
                $requete->andWhere('beg.id in(:eau)');
                $requete->setParameter(':eau', $search['eauMultiples']);
            } else {
                $requete->andWhere('beg.id = :eau');
                $requete->setParameter(':eau', $search['eauMultiples'][0]);
            }
            /*$requete->andWhere('beg.id = :eau');
            $requete->setParameter(':eau', $search['eau']);*/
        }
        if (!empty($search['entite_sous_type_multiples'])) {
            if (count($search['entite_sous_type_multiples']) > 1) {
                $requete->andWhere('est.id in (:sous_type)');
                $requete->setParameter(':sous_type', $search['entite_sous_type_multiples']);
            } else {
                $requete->andWhere('est.id = :sous_type');
                $requete->setParameter(':sous_type', $search['entite_sous_type_multiples'][0]);
            }
        }
        if (!empty($search['marque'])) {
            $requete->andWhere('mar.id = :marque');
            $requete->setParameter(':marque', $search['marque']);
        }
        if (!empty($search['matiere'])) {
            $requete->andWhere('mat.id = :matiere');
            $requete->setParameter(':matiere', $search['matiere']);
        }
        if (!empty($search['precipitation'])) {
            $requete->andWhere('pr.id = :precipitation');
            $requete->setParameter(':precipitation', $search['precipitation']);
        }
        if (!empty($search['rusticiteMultiples'])) {
            $rust_min = null;
            $rust_max = null;

            $origineCarte = isset($search['origineCarte']) ? $search['origineCarte'] : null;
            $rustSearched = $em->getRepository('App\Core\Entity\Rusticite')->findByIds($search['rusticiteMultiples'], $origineCarte);
            foreach ($rustSearched as $item) {
                if ($rust_min === null || $item->getMin() <= $rust_min) {
                    $rust_min = $item->getMin();
                }

                if ($rust_max === null || $item->getMin() >= $rust_max) {
                    $rust_max = $item->getMin();
                }
            }

            if (count($rustSearched) > 1) {
                $orModule = $requete->expr()->orX(
                    $requete->expr()->eq('e.annuelle', '1'),
                    $requete->expr()->andX(
                        $requete->expr()->lte('e.rusticiteValeur', ':rusticite_max'),
                        $requete->expr()->gte('e.rusticiteValeur', ':rusticite_min')
                    ),
                    $requete->expr()->andX(
                        $requete->expr()->lte('rm.min', ':rusticite_max'),
                        $requete->expr()->gte('rm.min', ':rusticite_min')
                    )
                );
                $requete->andWhere($orModule);
                $requete->setParameter(':rusticite_min', $rust_min);
                $requete->setParameter(':rusticite_max', $rust_max);
            } else {
                $orModule = $requete->expr()->orX(
                    $requete->expr()->eq('e.annuelle', '1'),
                    $requete->expr()->andX(
                        $requete->expr()->lte('e.rusticiteValeur', ':rusticite_max'),
                        $requete->expr()->gte('e.rusticiteValeur', ':rusticite_min')
                    ),
                    $requete->expr()->andX(
                        $requete->expr()->lte('rm.min', ':rusticite_max'),
                        $requete->expr()->gte('rm.min', ':rusticite_min')
                    )
                );
                $requete->andWhere($orModule);
                $requete->setParameter(':rusticite_min', $rust_min);
                $requete->setParameter(':rusticite_max', $rust_max);
            }
        }

        if (($entiteType->getId() == 1 || $entiteType->getId() == 2) && $precipitationMax !== null) {
            $requete->andWhere('pr.id <= :precipitationMax OR bm.id IS NULL');
            $requete->setParameter(':precipitationMax', $precipitationMax);
        }

        if ($entiteType->getId() == 2) {
            $requete->andWhere('(ct.id = :creationTypeId OR ct.id IS NULL)');
            $requete->setParameter(':creationTypeId', $creationTypeId);
            if ($surface && $surface > 0) { //filtre surface
                $requete->andWhere(
                    '(comp.nbCasesX*comp.nbCasesY*comp.espacementObjet*comp.espacementObjet <= :creationSurface '
                    . 'OR comp.nbCasesX = 0 '
                    . 'OR comp.nbCasesX IS NULL '
                    . 'OR comp.nbCasesY = 0 '
                    . 'OR comp.nbCasesY IS NULL '
                    . 'OR comp.espacementObjet = 0 '
                    . 'OR comp.espacementObjet IS NULL)'
                );
                $requete->setParameter(':creationSurface', $surface * 10000); // surface en m² convertie en cm²
            }
        }

        if (($entiteType->getId() == 3 || $entiteType->getId() == 4) && $surface && $surface > 0) {//filtre surface
            $requete->andWhere(
                '(e.diametrePot*e.diametrePot <= :creationSurface OR e.diametrePot = 0 OR e.diametrePot IS NULL)'
            );
            $requete->setParameter(':creationSurface', $surface * 10000);
        }

        // Permet de ne sélectionner qu'une seule entité parmi les variants de taille (avec le prix mini)
        $sql = 'SELECT entite00.id FROM entite entite00 INNER JOIN variant_taille var01 ON entite00.entite_variant_taille = var01.id WHERE entite00.actif = 1 AND entite00.id = (SELECT entite01.id FROM entite entite01 INNER JOIN variant_taille var02 ON entite01.entite_variant_taille = var02.id WHERE var01.id = var02.id AND entite01.actif = 1 ORDER BY entite01.prix_mini ASC LIMIT 1)';
        $query = $em->getConnection()->prepare($sql);
        $query->execute();
        $variantes = $query->fetchAll();

        $requete->andWhere(
            $requete->expr()->orX(
                $requete->expr()->isNull('e.variantTaille'),
                $requete->expr()->in('e.id', ':variantes')
            )
        );
        $requete->setParameter('variantes', $variantes);


        $requete->orderBy('e.pictoNouveauComputedFlag + e.pictoPromoComputedFlag + e.pictoCoupCoeurComputedFlag', 'DESC');
        $requete->addOrderBy('e.nom', 'ASC');

        /*
        dump('-----------');
        dump($requete->getQuery()->getParameters());
        dump($requete->getQuery()->getSql());
        */

        if ($return == 'result') {
            $requete->groupBy('e.id');
            //$requete->orderBy('e.nom', 'ASC');
            $requete->setMaxResults($nbResultat);
            $requete->setFirstResult($depart);

            return $requete->getQuery()->getResult();
        } else {
            $rootAlias = $requete->getRootAliases()[0];

            $nbrResultsQuery = clone $requete;
            $nbrResultsQuery->resetDQLPart('select');
            $nbrResultsQuery->addSelect('COUNT(DISTINCT ' . $rootAlias . ') as nbr_resultats');

            return $nbrResultsQuery->getQuery()->getArrayResult()[0]['nbr_resultats'];
        }
    }

    public function recupDepuisFiltreLasso($nbResultat = 16, $depart = 0, $return, $creationTypeId, $surface)
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();

        $requete->addSelect('e, ep');
        $requete->from(Entite::class, 'e');
        $requete->innerJoin('e.entiteType', 'et');
        $requete->innerJoin('e.entitePhotos', 'ep');
        $requete->leftJoin('e.besoinEauMultiples', 'bm');
        $requete->leftJoin('bm.precipitations', 'pr');
        $requete->leftJoin('e.creationTypes', 'ct');
        $requete->where('e.lasso = true');
        $requete->andWhere('ep.hauteurEntite > 0');
        $requete->andWhere('e.actif = 1');

        // Permet de ne sélectionner qu'une seule entité parmi les variants de taille (avec le prix mini)
        $sql = 'SELECT entite00.id FROM entite entite00 '
            . 'INNER JOIN variant_taille var01 ON entite00.entite_variant_taille = var01.id '
            . 'WHERE entite00.actif = 1 AND entite00.id = ('
            . 'SELECT entite01.id FROM entite entite01 '
            . 'INNER JOIN variant_taille var02 ON entite01.entite_variant_taille = var02.id '
            . ' WHERE var01.id = var02.id AND entite01.actif = 1 ORDER BY entite01.prix_mini ASC LIMIT 1)';
        $query = $em->getConnection()->prepare($sql);
        $query->execute();
        $variantes = $query->fetchAll();
        $requete->andWhere(
            $requete->expr()->orX(
                $requete->expr()->isNull('e.variantTaille'),
                $requete->expr()->in('e.id', ':variantes')
            )
        );
        $requete->setParameter('variantes', $variantes);

        $requete->groupBy('e.id');

        if ($return == 'result') {
            $requete->orderBy('e.nom', 'ASC');
            $requete->setMaxResults($nbResultat);
            $requete->setFirstResult($depart);
            return $requete->getQuery()->getResult();
        } else {
            return count($requete->getQuery()->getResult());
        }
    }

    public function findByCreationId($creationId)
    {
        $requete = $this->createQueryBuilder('e')
            ->select('e')
            ->innerJoin('e.creationEntites', 'ce')
            ->innerJoin('ce.creation', 'c')
            ->where('c.id = :creation_id')
            ->andWhere('ce.visibilite = 1')
            ->orderBy('e.nom');

        $requete->setParameter(':creation_id', $creationId);

        return $requete->getQuery()->execute();
    }

    public function findAllByNom($nom)
    {
        $em = $this->getEntityManager()->getConnection();
        $results = $em->prepare(
            'SELECT e.id as id, et.nom as type, est.nom as sous_type, e.acronyme as acronyme, e.nom_vernaculaire as nom_vernaculaire, e.nom as nom, e.pot as pot, e.diametre_pot as diametre_pot, e.hauteur_pot as hauteur_pot,
                    (SELECT GROUP_CONCAT( c1.nom SEPARATOR ",") FROM entite_couleur ec INNER JOIN couleur c1 ON c1.id = ec.couleur_id WHERE ec.entite_id = e.id ORDER BY c1.nom) as couleurs,
                    (SELECT GROUP_CONCAT( c2.nom SEPARATOR ",") FROM entite_couleur_fleur ecf INNER JOIN couleur c2 ON c2.id = ecf.couleur_id WHERE ecf.entite_id = e.id ORDER BY c2.nom) as couleurs_fleurs
                    FROM entite e
                    INNER JOIN entite_type et ON et.id = e.entite_type_id
                    INNER JOIN entite_photo ep ON ep.entite_id = e.id
                    LEFT JOIN entite_sous_type est ON est.id = e.entite_sous_type_id
                    WHERE (e.nom_vernaculaire LIKE :nom OR e.nom LIKE :nom)
                    AND ep.nom NOT LIKE :exeptImage
                    AND ep.nom IS NOT NULL
                    AND et.id <> 2
                    GROUP BY e.id
                    ORDER BY e.nom_vernaculaire'
        );

        $results->bindValue(':nom', '%' . $nom . '%');
        $results->bindValue(':exeptImage', '%rien.png%');
        $results->execute();

        $entites = $results->fetchAll();

        return $entites;
    }

    /**
     * Retourne la liste des entités avec les informations liées pour le fichier d'export au format csv
     *
     * @return array
     */
    public function getEntitesForCsvExport($locale = "fr")
    {
        $em = $this->getEntityManager()->getConnection();
        $query = $em->query(
            "SELECT
                                        e.id,
                                        et.nom as type,
                                        e.acronyme,
                                        e.nom,
                                        e.nom_vernaculaire,
                                        (SELECT GROUP_CONCAT(eest.sous_type_id SEPARATOR ',') FROM entite_entitesoustype eest WHERE eest.entite_id = e.id) as sous_type,
                                        e.prix_mini,
                                        e.gratuit,
                                        e.rusticite_valeur,
                                        (SELECT GROUP_CONCAT(be.valeur SEPARATOR ',') FROM entite_besoin_eau ebe INNER JOIN besoin_eau be on (be.id = ebe.besoin_eau_id) WHERE ebe.entite_id = e.id) as besoin_eau,
                                        IF(em_1.mois_id IS NULL, '', '1') as janvier,
                                        IF(em_2.mois_id IS NULL, '', '1') as fevrier,
                                        IF(em_3.mois_id IS NULL, '', '1') as mars,
                                        IF(em_4.mois_id IS NULL, '', '1') as avril,
                                        IF(em_5.mois_id IS NULL, '', '1') as mai,
                                        IF(em_6.mois_id IS NULL, '', '1') as juin,
                                        IF(em_7.mois_id IS NULL, '', '1') as juillet,
                                        IF(em_8.mois_id IS NULL, '', '1') as aout,
                                        IF(em_9.mois_id IS NULL, '', '1') as septembre,
                                        IF(em_10.mois_id IS NULL, '', '1') as octobre,
                                        IF(em_11.mois_id IS NULL, '', '1') as novembre,
                                        IF(em_12.mois_id IS NULL, '', '1') as decembre,
                                        (SELECT GROUP_CONCAT( ec.couleur_id SEPARATOR ',') FROM entite_couleur ec WHERE ec.entite_id = e.id ORDER BY ec.couleur_id) as couleurs,
                                        (SELECT GROUP_CONCAT( ecf.couleur_id SEPARATOR ',') FROM entite_couleur_fleur ecf WHERE ecf.entite_id = e.id ORDER BY ecf.couleur_id) as couleurs_fleurs,
                                        (SELECT GROUP_CONCAT( ee.ensoleillement_id SEPARATOR ',') FROM entite_ensoleillement ee WHERE ee.entite_id = e.id ORDER BY ee.ensoleillement_id) as ensoleillements,
                                        (SELECT GROUP_CONCAT( ets.type_sol_id SEPARATOR ',') FROM entite_type_sol ets WHERE ets.entite_id = e.id ORDER BY ets.type_sol_id) as types_sols,
                                        (SELECT GROUP_CONCAT( es.style_id SEPARATOR ',') FROM entite_style es WHERE es.entite_id = e.id ORDER BY es.style_id) as styles,
                                        (SELECT GROUP_CONCAT( eca.categorie_id SEPARATOR ',') FROM entite_categorie eca WHERE eca.entite_id = e.id ORDER BY eca.categorie_id) as categories,
                                        (SELECT GROUP_CONCAT( em.matiere_id SEPARATOR ',') FROM entite_matiere em WHERE em.entite_id = e.id ORDER BY em.matiere_id) as matieres,
                                        m.nom as marque,
                                        e.pot,
                                        e.diametre_pot,
                                        e.hauteur_pot,
                                        e.diametre_final,
                                        e.hauteur_finale,
                                        e.caduc_persistant,
                                        e.toxique_alimentaire,
                                        e.toxique_alimentaire_information,
                                        e.divers,
                                        e.conseil_printemps,
                                        e.conseil_ete,
                                        e.conseil_automne,
                                        e.conseil_hiver,
                                        e.entretien_id as entretien,
                                        e.annuelle as annuelle,
                                        (SELECT ep.photo FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 1 AND ep.entite_photo_etat_id = 1 ORDER BY ep.id LIMIT 1) as photo_fleurie_0an,
                                        (SELECT ep.hauteur_entite FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 1 AND ep.entite_photo_etat_id = 1 ORDER BY ep.id LIMIT 1) as hauteur_fleurie_0an,
                                        (SELECT ep.photo FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 1 AND ep.entite_photo_etat_id = 2 ORDER BY ep.id LIMIT 1) as photo_non_fleurie_0an,
                                        (SELECT ep.hauteur_entite FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 1 AND ep.entite_photo_etat_id = 2 ORDER BY ep.id LIMIT 1) as hauteur_non_fleurie_0an,
                                        (SELECT ep.photo FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 1 AND ep.entite_photo_etat_id = 3 ORDER BY ep.id LIMIT 1) as photo_feuille_automne_0an,
                                        (SELECT ep.hauteur_entite FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 1 AND ep.entite_photo_etat_id = 3 ORDER BY ep.id LIMIT 1) as hauteur_feuille_automne_0an,
                                        (SELECT ep.photo FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 1 AND ep.entite_photo_etat_id = 4 ORDER BY ep.id LIMIT 1) as photo_sans_feuille_0an,
                                        (SELECT ep.hauteur_entite FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 1 AND ep.entite_photo_etat_id = 4 ORDER BY ep.id LIMIT 1) as hauteur_sans_feuille_0an,
                                        (SELECT ep.photo FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 2 AND ep.entite_photo_etat_id = 1 ORDER BY ep.id LIMIT 1) as photo_fleurie_2an,
                                        (SELECT ep.hauteur_entite FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 2 AND ep.entite_photo_etat_id = 1 ORDER BY ep.id LIMIT 1) as hauteur_fleurie_2an,
                                        (SELECT ep.photo FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 2 AND ep.entite_photo_etat_id = 2 ORDER BY ep.id LIMIT 1) as photo_non_fleurie_2an,
                                        (SELECT ep.hauteur_entite FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 2 AND ep.entite_photo_etat_id = 2 ORDER BY ep.id LIMIT 1) as hauteur_non_fleurie_2an,
                                        (SELECT ep.photo FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 2 AND ep.entite_photo_etat_id = 3 ORDER BY ep.id LIMIT 1) as photo_feuille_automne_2an,
                                        (SELECT ep.hauteur_entite FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 2 AND ep.entite_photo_etat_id = 3 ORDER BY ep.id LIMIT 1) as hauteur_feuille_automne_2an,
                                        (SELECT ep.photo FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 2 AND ep.entite_photo_etat_id = 4 ORDER BY ep.id LIMIT 1) as photo_sans_feuille_2an,
                                        (SELECT ep.hauteur_entite FROM entite_photo ep WHERE ep.entite_id = e.id AND ep.annee_id = 2 AND ep.entite_photo_etat_id = 4 ORDER BY ep.id LIMIT 1) as hauteur_sans_feuille_2an,
                                        e.lasso,
                                        e.lasso_photo,
                                        (SELECT GROUP_CONCAT(er.rusticite_id SEPARATOR ',') FROM entite_rusticite er WHERE er.entite_id = e.id) as rusticite_id
                                    FROM entite e
                                    INNER JOIN entite_type et ON et.id = e.entite_type_id
                                    LEFT JOIN marque m ON m.id = e.marque_id
                                    LEFT JOIN entretien en ON en.id = e.entretien_id
                                    LEFT JOIN rusticite r ON r.id = e.rusticite_id
                                    LEFT JOIN besoin_eau be ON be.id = e.besoin_eau_id
                                    LEFT JOIN entite_sous_type est ON est.id = e.entite_sous_type_id
                                    LEFT JOIN entite_mois em_1 ON em_1.entite_id = e.id AND em_1.mois_id = 1
                                    LEFT JOIN entite_mois em_2 ON em_2.entite_id = e.id AND em_2.mois_id = 2
                                    LEFT JOIN entite_mois em_3 ON em_3.entite_id = e.id AND em_3.mois_id = 3
                                    LEFT JOIN entite_mois em_4 ON em_4.entite_id = e.id AND em_4.mois_id = 4
                                    LEFT JOIN entite_mois em_5 ON em_5.entite_id = e.id AND em_5.mois_id = 5
                                    LEFT JOIN entite_mois em_6 ON em_6.entite_id = e.id AND em_6.mois_id = 6
                                    LEFT JOIN entite_mois em_7 ON em_7.entite_id = e.id AND em_7.mois_id = 7
                                    LEFT JOIN entite_mois em_8 ON em_8.entite_id = e.id AND em_8.mois_id = 8
                                    LEFT JOIN entite_mois em_9 ON em_9.entite_id = e.id AND em_9.mois_id = 9
                                    LEFT JOIN entite_mois em_10 ON em_10.entite_id = e.id AND em_10.mois_id = 10
                                    LEFT JOIN entite_mois em_11 ON em_11.entite_id = e.id AND em_11.mois_id = 11
                                    LEFT JOIN entite_mois em_12 ON em_12.entite_id = e.id AND em_12.mois_id = 12
                                    WHERE et.id != 2
                                    AND e.actif = 1
                                    "
        );

        $results = $query->fetchAll(\PDO::FETCH_ASSOC);

        $ids = array();
        foreach ($results as $item) {
            $ids[] = $item['id'];
        }

        if($locale !== null) {
            $fieldsToTranslate = array(
                "nom" => "nom",
                "nomVernaculaire" => "nom_vernaculaire",
                "conseilAutomne" => "conseil_automne",
                "conseilHiver" => "conseil_hiver",
                "conseilPrintemps" => "conseil_printemps",
                "conseilEte" => "conseil_ete",
                "divers" => "divers"
            );
            $translatedFields = $this->_em->getRepository(\App\Core\Entity\Entite::class)->getTranslationForFieldsAndIds(array_keys($fieldsToTranslate), $ids, $locale);

            foreach ($results as &$item) {
                foreach ($fieldsToTranslate as $key => $sqlName) {
                    $valueToOutput = "___locale:fr " . $item[$sqlName] . " ___locale";
                    if (isset($translatedFields[$item['id']][$key . '_trans'])) {
                        $valueToOutput .= "    ";
                        $valueToOutput .= "___locale:" . $locale . " " . $translatedFields[$item['id']][$key . '_trans'] . " ___locale";
                    }

                    $item[$sqlName] = $valueToOutput;
                }
            }
        }

        return $results;
    }

    public function findForExportClassique($row, $indexLigne)
    {

        $entityFound = null;
        $validEntity = false;

        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('e');
        $requete->from('App\Core\Entity\Entite', 'e');
        $requete->leftJoin('e.translations', 't');
        $requete->addSelect('t');

        $rowId = "";
        $rowNom = "";
        $rowNomVernaculaire = "";

        if (isset($row['id']) && trim($row['id']) != "") {
            $rowId = trim($row['id']);
        }

        if (isset($row['nom']) && (is_array($row['nom']) || trim($row['nom']) != "")) {
            if (is_array($row['nom'])) {
                $rowNom = mb_strtolower(trim($row['nom']['translation']['fr']['translation']), 'UTF-8');
            } else {
                $rowNom = mb_strtolower(trim($row['nom']), 'UTF-8');
            }
        }

        if (isset($row['nom_vernaculaire']) && (is_array($row['nom_vernaculaire']) || trim($row['nom_vernaculaire']) != "")) {
            if (is_array($row['nom_vernaculaire'])) {
                $rowNomVernaculaire = mb_strtolower(trim($row['nom_vernaculaire']['translation']['fr']['translation']), 'UTF-8');
            } else {
                $rowNomVernaculaire = mb_strtolower(trim($row['nom_vernaculaire']), 'UTF-8');
            }
        }

        if ($rowId !== "") {
            $requete->where('e.id = :id');
            $requete->setParameter(':id', $rowId);
        } else if ($rowNom !== "") {
            $requete->where('e.nom = :nom');
            $requete->setParameter(':nom', $rowNom);
        } else if ($rowNomVernaculaire !== "") {
            $requete->where('e.nomVernaculaire = :nom_vernaculaire');
            $requete->setParameter(':nom_vernaculaire', $rowNomVernaculaire);
        }

        $requete->andWhere('e.actif = 1');
        $res = $requete->getQuery()->getResult();

        if (count($res) > 1) {
            throw new \Exception("Plusieurs Entites trouves pour la ligne " . $indexLigne);
        }

        if (count($res) == 0) {
            $entityFound = null;
        } else {
            $entityFound = $res[0];
            $nomValid = false;
            $nomVernaculaireValid = false;

            $entiteNom = $entityFound->getNom() !== null ? mb_strtolower(trim($entityFound->getNom()), 'UTF-8') : null;
            if (($entiteNom === null && trim($rowNom) == "") || (trim($entiteNom) == trim($rowNom))) {
                $nomValid = true;
            }

            $entiteNomVernaculaire = $entityFound->getNomVernaculaire() !== null ? mb_strtolower(trim($entityFound->getNomVernaculaire()), 'UTF-8') : null;
            if (($entiteNomVernaculaire === null && trim($rowNomVernaculaire) == "") || (trim($entiteNomVernaculaire) == trim($rowNomVernaculaire))) {
                $nomVernaculaireValid = true;
            }

            if ($nomValid === true) {
                $validEntity = true;
            }
        }

        if ($entityFound !== null && $validEntity === false) {
            throw new \Exception("Entites ambigues pour la ligne " . $indexLigne);
        }

        return $entityFound;
    }

    public function getQueryEntitesWithPictogrammeToUpdate()
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();

        $requete->addSelect('e');
        $requete->from('App\Core\Entity\Entite', 'e');
        $requete->where('e.pictoNouveau = true');
        $requete->orWhere('e.pictoPromo = true');
        $requete->orWhere('e.pictoCoupCoeur = true');

        return $requete;
    }

    public function getQueryEntitesAvecPlusieursPhotoPrincipales($refImport = null, $mode = 'OLDEST_PHOTO')
    {
        $em = $this->getEntityManager();

        $req = $em->createQueryBuilder();
        $req->select('e.id, count(ep.id) as nbr_photos')
            ->from('App\Core\Entity\Entite', 'e', 'e.id')
            ->innerJoin('e.entitePhotos', 'ep')
            ->where('ep.principale = 1')
            ->andWhere('e.actif = 1')
            ->groupBy('e.id')
            ->having('nbr_photos > 1');

        if ($mode == 'LAST_IMPORTED_PHOTO') {
            $req->andWhere('e.identifiantDernierImport = :identifiantImport');
            $req->setParameter(':identifiantImport', $refImport);
        }

        $res = $req->getQuery()->getArrayResult();
        $entiteIds = array_keys($res);

        if ($mode == 'OLDEST_PHOTO') {
            $reqPhotoIdToPromote = $em->createQueryBuilder()
                ->select('e.id as entite_id, ep.id as entite_photo_id')
                ->from(EntitePhoto::class, 'ep')
                ->innerJoin(Entite::class, 'e', 'with', 'IDENTITY(ep.entite) = e.id')
                ->leftJoin(EntitePhoto::class, 'ep2', 'with', 'IDENTITY(ep.entite) = IDENTITY(ep2.entite) AND ep2.id < ep.id')
                ->where('e.id in(:entiteIds)')
                ->andWhere('ep2.id is null')
                ->setParameter(':entiteIds', $entiteIds);
            $photoIdsToPromote = $reqPhotoIdToPromote->getQuery()->getArrayResult();

            foreach ($photoIdsToPromote as $photoItem) {
                $res[$photoItem['entite_id']]['photoToPromote'] = $photoItem['entite_photo_id'];
            }

            return $res;
        } else if ($mode == 'LAST_IMPORTED_PHOTO') {
            $reqPhotoIdToPromote = $em->createQueryBuilder()
                ->select('e')
                ->from(\App\Core\Entity\Entite::class, 'e')
                ->where('e.id in (:entiteIds)')
                ->setParameter(':entiteIds', $entiteIds);

            $photoIdsToPromote = $reqPhotoIdToPromote->getQuery()->getResult();
            foreach ($photoIdsToPromote as $photoItem) {
                if ($photoItem->getDernierePhotoPrincipaleImporte() !== null) {
                    $res[$photoItem->getId()]['photoToPromote'] = $photoItem->getDernierePhotoPrincipaleImporte()->getId();
                }
            }

            return $res;
        }
    }

    public function getTranslationForFieldsAndIds($fields = array(), $ids = array(), $locale)
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();

        $requete->addSelect('e.id');
        $requete->from('App\Core\Entity\Entite', 'e', 'e.id');
        $requete->andWhere('e.id in (:ids)');
        $requete->setParameter(':ids', $ids);

        foreach ($fields as $fieldName) {
            $alias = 'tr' . $fieldName;
            $requete->leftJoin("e.translations", $alias, "with", $alias . ".object = e.id and "
                . $alias . ".locale = " . "'" . $locale . "'" . " and " . $alias . ".field = " . "'" . $fieldName . "'");
            $requete->addSelect($alias . '.content' . ' ' . $fieldName . '_trans');
        }

        return $requete->getQuery()->getResult();
    }
}
