<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntiteSousTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntiteSousTypeRepository extends EntityRepository
{

    public function findAllArray()
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('c.nom');
        $requete->from('App\Core\Entity\EntiteSousType', 'c');
        $list = $requete->getQuery()->getArrayResult();

        $tab = array();
        foreach ($list as $value) {
            $tab[] = $value['nom'];
        }

        return $tab;
    }

    public function findByIds($sousTypeIds)
    {
        $res = array();

        if (is_array($sousTypeIds) && count($sousTypeIds) > 0) {
            $em = $this->getEntityManager();
            $requete = $em->createQueryBuilder();
            $requete->addSelect('est');
            $requete->from('App\Core\Entity\EntiteSousType', 'est');
            $requete->where('est.id IN(:sousTypeIds)');
            $requete->setParameter(':sousTypeIds', $sousTypeIds);

            $res = $requete->getQuery()->getResult();
        }

        return $res;
    }
}
