<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntretienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntretienRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->createQueryBuilder('e')->addOrderBy('e.nom', "ASC");
    }

    public function recupNomsOrdonne()
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('e.id, e.nom');
        $requete->from('App\Core\Entity\Entretien', 'e');
        $requete->orderBy('e.nom', 'ASC');

        return $requete->getQuery()->getArrayResult();
    }

}
