<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoisRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->createQueryBuilder('m')->addOrderBy('m.nom', "ASC");
    }

    public function recupNomsOrdonne()
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('m.id, m.nom');
        $requete->from('App\Core\Entity\Mois', 'm');
        $requete->orderBy('m.id', 'ASC');

        return $requete->getQuery()->getArrayResult();
    }

}
