<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends EntityRepository
{
    public function findAllOrderedByPrice(bool $withFree = true)
    {
        $query = $this->createQueryBuilder('o')
            ->orderBy('o.prix', 'ASC');

        if (!$withFree) {
            $query->where('o.prix > 0');
        }

        return $query->getQuery()->getResult();
    }

}
