<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->createQueryBuilder('p')->addOrderBy('p.min', "ASC");
    }

}
