<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrecipitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecipitationRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->createQueryBuilder('p')->addOrderBy('p.min', "ASC");
    }

    public function recupValeurMax()
    {
        $query = $this->createQueryBuilder('pr');
        $query->select('pr, MAX(pr.id) AS id_max');
        $query->setMaxResults(1);
        $query->orderBy('id_max', 'DESC');

        return $query->getQuery()->getResult();
    }

}
