<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends EntityRepository
{
    public function recupOrdreDateDescParClient($clientId)
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('p');
        $requete->from('App\Core\Entity\Projet', 'p');
        $requete->where('p.client = :clientId');
        $requete->andWhere('p.confirmer = 1');
        $requete->orderBy('p.dateCreation', 'DESC');
        $requete->setParameter(':clientId', $clientId);

        return $requete->getQuery()->getResult();
    }

    public function recupOrdreMajParClient($clientId)
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('p')
            ->from('App\Core\Entity\Projet', 'p')
            ->where('p.client = :clientId')
            ->andWhere('p.confirmer = 1')
            ->leftJoin('p.creations', 'c')
            ->orderBy('p.dateCreation', 'DESC')
            ->orderBy('c.dateModification', 'DESC')
            ->setParameter(':clientId', $clientId);


        return $requete->getQuery()->getResult();
    }

}
