<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RusticiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RusticiteRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->createQueryBuilder('r')->addOrderBy('r.min', "ASC");
    }

    public function recupOneParValeur($val)
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('r');
        $requete->from('App\Core\Entity\Rusticite', 'r');
        $requete->where('r.min <= :val');
        $requete->andWhere('r.max >= :val');
        $requete->setParameter(':val', $val);

        $res = $requete->getQuery()->getResult();
        return $res[0];
    }

    public function findByIds($rusticiteIds, $origineCarte = null, $orderedByProperty = null)
    {
        $res = array();
        $em = $this->getEntityManager();
        $rusticiteToRegroup = array();

        $rusticiteListIndexedByName = $this->getAllIndexedBy('name');
        $rusticiteListIndexedById = $this->getAllIndexedBy('id');

        if($origineCarte !== null && $origineCarte == "FR") {
            $tmpRusticiteIds = array();
            foreach($rusticiteIds as $rusticiteId) {
                $matchedRusticite = $rusticiteListIndexedById[$rusticiteId];
                if(!in_array($matchedRusticite->getNom(), $rusticiteToRegroup)) {
                    $tmpRusticiteIds[] = $rusticiteId;
                } else {
                    $nomRusticite = $matchedRusticite->getNom();

                    $regexpMatch = array();
                    if(preg_match('/a/', $nomRusticite, $regexpMatch) == 1) {
                        $groupedRusticiteName = str_replace('a', '', $nomRusticite);
                    } else if(preg_match('/b/', $nomRusticite, $regexpMatch) == 1) {
                        $groupedRusticiteName = str_replace('b', '', $nomRusticite);
                    }

                    $tmpRusticiteIds[] = (string)$rusticiteListIndexedByName[$groupedRusticiteName]->getId();
                }
            }

            $tmpRusticiteIds = array_unique($tmpRusticiteIds);
            $rusticiteIds = $tmpRusticiteIds;
        }

        if (is_array($rusticiteIds) && count($rusticiteIds) > 0) {
            $requete = $em->createQueryBuilder();
            $requete->addSelect('r');

            if($orderedByProperty === null) {
                $requete->from('App\Core\Entity\Rusticite', 'r');
            } else {
                $requete->from('App\Core\Entity\Rusticite', 'r', 'r.' . $orderedByProperty);
            }

            $requete->where('r.id IN(:rusticiteIds)');
            $requete->setParameter(':rusticiteIds', $rusticiteIds);

            $res = $requete->getQuery()->getResult();
        } else if($rusticiteIds == '*') {
            $em = $this->getEntityManager();
            $requete = $em->createQueryBuilder();
            $requete->addSelect('r');

            if($orderedByProperty === null) {
                $requete->from('App\Core\Entity\Rusticite', 'r');
            } else {
                $requete->from('App\Core\Entity\Rusticite', 'r', 'r.' . $orderedByProperty);
            }

            $res = $requete->getQuery()->getResult();
        }

        return $res;
    }

    public function getAllIndexedBy($indexer = 'id')
    {
        $em = $this->getEntityManager();

        if($indexer == 'name') {
            $query =  $em->createQueryBuilder()
                ->addSelect('r')
                ->from('App:Rusticite', 'r', 'r.nom');
        } else if($indexer == 'id') {
            $query =  $em->createQueryBuilder()
                ->addSelect('r')
                ->from('App:Rusticite', 'r', 'r.id');
        }

        return $query->getQuery()->getResult();

    }
}
