<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StyleRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->createQueryBuilder('s')->addOrderBy('s.nom', "ASC");
    }

    public function recupNomsOrdonne()
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('s.id, s.nom');
        $requete->from('App\Core\Entity\Style', 's');
        $requete->orderBy('s.nom', 'ASC');

        return $requete->getQuery()->getArrayResult();
    }

}
