<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeSolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSolRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->createQueryBuilder('ts')->addOrderBy('ts.nom', "ASC");
    }

    public function recupNomsOrdonne()
    {
        $em = $this->getEntityManager();
        $requete = $em->createQueryBuilder();
        $requete->addSelect('ts.id, ts.nom');
        $requete->from('App\Core\Entity\TypeSol', 'ts');
        $requete->orderBy('ts.nom', 'ASC');

        return $requete->getQuery()->getArrayResult();
    }

}
