<?php

namespace App\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VariantCouleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariantCouleurRepository extends EntityRepository
{
}
